version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - gradle wrapper --gradle-version 2.11
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes