version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ls
      - ./gradlew bootJar
      - cd ./build/libs
      - ls
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - ls
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
    - Procfile
  discard-paths: yes